# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
/run/verbose 2
# 
# protons @ 200 MeV originating from a large spherical surface of radius 200 cm, distributed isotropically


/gps/particle proton

/gps/pos/type Surface 

/gps/pos/shape Sphere 

/gps/pos/centre 0 0 0 cm 

/gps/pos/radius 500 cm 

/gps/ang/type iso 

/gps/ene/type Mono 

/gps/ene/mono 200 MeV 

/run/beamOn 100000
